#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

#runApplication blockMesh
#runApplication snappyHexMesh -overwrite
ideasUnvToFoam fluidCellFins.unv
transformPoints "scale=(0.001 0.001 0.001)"
runApplication splitMeshRegions -cellZones -overwrite
runApplication decomposePar -allRegions
runParallel $(getApplication)
runApplication reconstructPar -allRegions
paraFoam -touchAll
